### ISSUE TITLE
POSTing form data gives "AttributeError: 'dict' object has no attribute 'dumps'"

### ISSUE THREAD

**Issue by LaundroMat** [iogf/sukhoi#6]
I'm trying to mine a page obtained by POSTing some form data to a URL.

    items = MyMiner(url, method="post", payload=form_data)

`form_data` is a simple dict. I'm getting this error:

```
Event:<class 'untwisted.event.SSL_CONNECT'>
Args:()
Traceback (most recent call last):
  File "[...]\lib\site-packages\untwisted\dispatcher.py", line 68, in driveµ
    handle(self, *params)
  File "[...]\lib\site-packages\websnake.py", line 304, in handle_connect
    data = self.payload.dumps(self)
AttributeError: 'dict' object has no attribute 'dumps'
```

**Comment by iogf** [comment]
You should wrap your dict with a websnake JSon class.
https://github.com/untwisted/websnake
